//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class GetActionServersResponse : Message
    {
        public const string k_RosMessageName = "rosapi/GetActionServers";
        public override string RosMessageName => k_RosMessageName;

        public string[] action_servers;

        public GetActionServersResponse()
        {
            this.action_servers = new string[0];
        }

        public GetActionServersResponse(string[] action_servers)
        {
            this.action_servers = action_servers;
        }

        public static GetActionServersResponse Deserialize(MessageDeserializer deserializer) => new GetActionServersResponse(deserializer);

        private GetActionServersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.action_servers, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.action_servers);
            serializer.Write(this.action_servers);
        }

        public override string ToString()
        {
            return "GetActionServersResponse: " +
            "\naction_servers: " + System.String.Join(", ", action_servers.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
