//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class GetParamNamesResponse : Message
    {
        public const string k_RosMessageName = "rosapi/GetParamNames";
        public override string RosMessageName => k_RosMessageName;

        public string[] names;

        public GetParamNamesResponse()
        {
            this.names = new string[0];
        }

        public GetParamNamesResponse(string[] names)
        {
            this.names = names;
        }

        public static GetParamNamesResponse Deserialize(MessageDeserializer deserializer) => new GetParamNamesResponse(deserializer);

        private GetParamNamesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.names, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.names);
            serializer.Write(this.names);
        }

        public override string ToString()
        {
            return "GetParamNamesResponse: " +
            "\nnames: " + System.String.Join(", ", names.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
