//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class GetParamNamesRequest : Message
    {
        public const string k_RosMessageName = "rosapi/GetParamNames";
        public override string RosMessageName => k_RosMessageName;


        public GetParamNamesRequest()
        {
        }
        public static GetParamNamesRequest Deserialize(MessageDeserializer deserializer) => new GetParamNamesRequest(deserializer);

        private GetParamNamesRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetParamNamesRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
