//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class GetParamResponse : Message
    {
        public const string k_RosMessageName = "rosapi/GetParam";
        public override string RosMessageName => k_RosMessageName;

        public string value;

        public GetParamResponse()
        {
            this.value = "";
        }

        public GetParamResponse(string value)
        {
            this.value = value;
        }

        public static GetParamResponse Deserialize(MessageDeserializer deserializer) => new GetParamResponse(deserializer);

        private GetParamResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "GetParamResponse: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
