//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class GetTimeResponse : Message
    {
        public const string k_RosMessageName = "rosapi/GetTime";
        public override string RosMessageName => k_RosMessageName;

        public TimeMsg time;

        public GetTimeResponse()
        {
            this.time = new TimeMsg();
        }

        public GetTimeResponse(TimeMsg time)
        {
            this.time = time;
        }

        public static GetTimeResponse Deserialize(MessageDeserializer deserializer) => new GetTimeResponse(deserializer);

        private GetTimeResponse(MessageDeserializer deserializer)
        {
            this.time = TimeMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.time);
        }

        public override string ToString()
        {
            return "GetTimeResponse: " +
            "\ntime: " + time.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
