//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class HasParamRequest : Message
    {
        public const string k_RosMessageName = "rosapi/HasParam";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public HasParamRequest()
        {
            this.name = "";
        }

        public HasParamRequest(string name)
        {
            this.name = name;
        }

        public static HasParamRequest Deserialize(MessageDeserializer deserializer) => new HasParamRequest(deserializer);

        private HasParamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "HasParamRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
