//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class NodeDetailsRequest : Message
    {
        public const string k_RosMessageName = "rosapi/NodeDetails";
        public override string RosMessageName => k_RosMessageName;

        public string node;

        public NodeDetailsRequest()
        {
            this.node = "";
        }

        public NodeDetailsRequest(string node)
        {
            this.node = node;
        }

        public static NodeDetailsRequest Deserialize(MessageDeserializer deserializer) => new NodeDetailsRequest(deserializer);

        private NodeDetailsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node);
        }

        public override string ToString()
        {
            return "NodeDetailsRequest: " +
            "\nnode: " + node.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
