//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class NodeDetailsResponse : Message
    {
        public const string k_RosMessageName = "rosapi/NodeDetails";
        public override string RosMessageName => k_RosMessageName;

        public string[] subscribing;
        public string[] publishing;
        public string[] services;

        public NodeDetailsResponse()
        {
            this.subscribing = new string[0];
            this.publishing = new string[0];
            this.services = new string[0];
        }

        public NodeDetailsResponse(string[] subscribing, string[] publishing, string[] services)
        {
            this.subscribing = subscribing;
            this.publishing = publishing;
            this.services = services;
        }

        public static NodeDetailsResponse Deserialize(MessageDeserializer deserializer) => new NodeDetailsResponse(deserializer);

        private NodeDetailsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.subscribing, deserializer.ReadLength());
            deserializer.Read(out this.publishing, deserializer.ReadLength());
            deserializer.Read(out this.services, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.subscribing);
            serializer.Write(this.subscribing);
            serializer.WriteLength(this.publishing);
            serializer.Write(this.publishing);
            serializer.WriteLength(this.services);
            serializer.Write(this.services);
        }

        public override string ToString()
        {
            return "NodeDetailsResponse: " +
            "\nsubscribing: " + System.String.Join(", ", subscribing.ToList()) +
            "\npublishing: " + System.String.Join(", ", publishing.ToList()) +
            "\nservices: " + System.String.Join(", ", services.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
