//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class PublishersResponse : Message
    {
        public const string k_RosMessageName = "rosapi/Publishers";
        public override string RosMessageName => k_RosMessageName;

        public string[] publishers;

        public PublishersResponse()
        {
            this.publishers = new string[0];
        }

        public PublishersResponse(string[] publishers)
        {
            this.publishers = publishers;
        }

        public static PublishersResponse Deserialize(MessageDeserializer deserializer) => new PublishersResponse(deserializer);

        private PublishersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.publishers, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.publishers);
            serializer.Write(this.publishers);
        }

        public override string ToString()
        {
            return "PublishersResponse: " +
            "\npublishers: " + System.String.Join(", ", publishers.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
