//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class SearchParamResponse : Message
    {
        public const string k_RosMessageName = "rosapi/SearchParam";
        public override string RosMessageName => k_RosMessageName;

        public string global_name;

        public SearchParamResponse()
        {
            this.global_name = "";
        }

        public SearchParamResponse(string global_name)
        {
            this.global_name = global_name;
        }

        public static SearchParamResponse Deserialize(MessageDeserializer deserializer) => new SearchParamResponse(deserializer);

        private SearchParamResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.global_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.global_name);
        }

        public override string ToString()
        {
            return "SearchParamResponse: " +
            "\nglobal_name: " + global_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
