//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class SearchParamRequest : Message
    {
        public const string k_RosMessageName = "rosapi/SearchParam";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public SearchParamRequest()
        {
            this.name = "";
        }

        public SearchParamRequest(string name)
        {
            this.name = name;
        }

        public static SearchParamRequest Deserialize(MessageDeserializer deserializer) => new SearchParamRequest(deserializer);

        private SearchParamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SearchParamRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
