//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServicesResponse : Message
    {
        public const string k_RosMessageName = "rosapi/Services";
        public override string RosMessageName => k_RosMessageName;

        public string[] services;

        public ServicesResponse()
        {
            this.services = new string[0];
        }

        public ServicesResponse(string[] services)
        {
            this.services = services;
        }

        public static ServicesResponse Deserialize(MessageDeserializer deserializer) => new ServicesResponse(deserializer);

        private ServicesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.services, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.services);
            serializer.Write(this.services);
        }

        public override string ToString()
        {
            return "ServicesResponse: " +
            "\nservices: " + System.String.Join(", ", services.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
