//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceNodeResponse : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceNode";
        public override string RosMessageName => k_RosMessageName;

        public string node;

        public ServiceNodeResponse()
        {
            this.node = "";
        }

        public ServiceNodeResponse(string node)
        {
            this.node = node;
        }

        public static ServiceNodeResponse Deserialize(MessageDeserializer deserializer) => new ServiceNodeResponse(deserializer);

        private ServiceNodeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.node);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.node);
        }

        public override string ToString()
        {
            return "ServiceNodeResponse: " +
            "\nnode: " + node.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
