//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceTypeResponse : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceType";
        public override string RosMessageName => k_RosMessageName;

        public string type;

        public ServiceTypeResponse()
        {
            this.type = "";
        }

        public ServiceTypeResponse(string type)
        {
            this.type = type;
        }

        public static ServiceTypeResponse Deserialize(MessageDeserializer deserializer) => new ServiceTypeResponse(deserializer);

        private ServiceTypeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "ServiceTypeResponse: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
