//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceRequestDetailsResponse : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceRequestDetails";
        public override string RosMessageName => k_RosMessageName;

        public TypeDefMsg[] typedefs;

        public ServiceRequestDetailsResponse()
        {
            this.typedefs = new TypeDefMsg[0];
        }

        public ServiceRequestDetailsResponse(TypeDefMsg[] typedefs)
        {
            this.typedefs = typedefs;
        }

        public static ServiceRequestDetailsResponse Deserialize(MessageDeserializer deserializer) => new ServiceRequestDetailsResponse(deserializer);

        private ServiceRequestDetailsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.typedefs, TypeDefMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.typedefs);
            serializer.Write(this.typedefs);
        }

        public override string ToString()
        {
            return "ServiceRequestDetailsResponse: " +
            "\ntypedefs: " + System.String.Join(", ", typedefs.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
