//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceRequestDetailsRequest : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceRequestDetails";
        public override string RosMessageName => k_RosMessageName;

        public string type;

        public ServiceRequestDetailsRequest()
        {
            this.type = "";
        }

        public ServiceRequestDetailsRequest(string type)
        {
            this.type = type;
        }

        public static ServiceRequestDetailsRequest Deserialize(MessageDeserializer deserializer) => new ServiceRequestDetailsRequest(deserializer);

        private ServiceRequestDetailsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "ServiceRequestDetailsRequest: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
