//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceHostRequest : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceHost";
        public override string RosMessageName => k_RosMessageName;

        public string service;

        public ServiceHostRequest()
        {
            this.service = "";
        }

        public ServiceHostRequest(string service)
        {
            this.service = service;
        }

        public static ServiceHostRequest Deserialize(MessageDeserializer deserializer) => new ServiceHostRequest(deserializer);

        private ServiceHostRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.service);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.service);
        }

        public override string ToString()
        {
            return "ServiceHostRequest: " +
            "\nservice: " + service.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
