//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class ServiceHostResponse : Message
    {
        public const string k_RosMessageName = "rosapi/ServiceHost";
        public override string RosMessageName => k_RosMessageName;

        public string host;

        public ServiceHostResponse()
        {
            this.host = "";
        }

        public ServiceHostResponse(string host)
        {
            this.host = host;
        }

        public static ServiceHostResponse Deserialize(MessageDeserializer deserializer) => new ServiceHostResponse(deserializer);

        private ServiceHostResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.host);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.host);
        }

        public override string ToString()
        {
            return "ServiceHostResponse: " +
            "\nhost: " + host.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
