//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class SetParamRequest : Message
    {
        public const string k_RosMessageName = "rosapi/SetParam";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public string value;

        public SetParamRequest()
        {
            this.name = "";
            this.value = "";
        }

        public SetParamRequest(string name, string value)
        {
            this.name = name;
            this.value = value;
        }

        public static SetParamRequest Deserialize(MessageDeserializer deserializer) => new SetParamRequest(deserializer);

        private SetParamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetParamRequest: " +
            "\nname: " + name.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
