//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class SubscribersResponse : Message
    {
        public const string k_RosMessageName = "rosapi/Subscribers";
        public override string RosMessageName => k_RosMessageName;

        public string[] subscribers;

        public SubscribersResponse()
        {
            this.subscribers = new string[0];
        }

        public SubscribersResponse(string[] subscribers)
        {
            this.subscribers = subscribers;
        }

        public static SubscribersResponse Deserialize(MessageDeserializer deserializer) => new SubscribersResponse(deserializer);

        private SubscribersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.subscribers, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.subscribers);
            serializer.Write(this.subscribers);
        }

        public override string ToString()
        {
            return "SubscribersResponse: " +
            "\nsubscribers: " + System.String.Join(", ", subscribers.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
