//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TopicTypeResponse : Message
    {
        public const string k_RosMessageName = "rosapi/TopicType";
        public override string RosMessageName => k_RosMessageName;

        public string type;

        public TopicTypeResponse()
        {
            this.type = "";
        }

        public TopicTypeResponse(string type)
        {
            this.type = type;
        }

        public static TopicTypeResponse Deserialize(MessageDeserializer deserializer) => new TopicTypeResponse(deserializer);

        private TopicTypeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "TopicTypeResponse: " +
            "\ntype: " + type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
