//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TopicTypeRequest : Message
    {
        public const string k_RosMessageName = "rosapi/TopicType";
        public override string RosMessageName => k_RosMessageName;

        public string topic;

        public TopicTypeRequest()
        {
            this.topic = "";
        }

        public TopicTypeRequest(string topic)
        {
            this.topic = topic;
        }

        public static TopicTypeRequest Deserialize(MessageDeserializer deserializer) => new TopicTypeRequest(deserializer);

        private TopicTypeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topic);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.topic);
        }

        public override string ToString()
        {
            return "TopicTypeRequest: " +
            "\ntopic: " + topic.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
