//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TopicsForTypeResponse : Message
    {
        public const string k_RosMessageName = "rosapi/TopicsForType";
        public override string RosMessageName => k_RosMessageName;

        public string[] topics;

        public TopicsForTypeResponse()
        {
            this.topics = new string[0];
        }

        public TopicsForTypeResponse(string[] topics)
        {
            this.topics = topics;
        }

        public static TopicsForTypeResponse Deserialize(MessageDeserializer deserializer) => new TopicsForTypeResponse(deserializer);

        private TopicsForTypeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topics, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
        }

        public override string ToString()
        {
            return "TopicsForTypeResponse: " +
            "\ntopics: " + System.String.Join(", ", topics.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
