//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TopicsResponse : Message
    {
        public const string k_RosMessageName = "rosapi/Topics";
        public override string RosMessageName => k_RosMessageName;

        public string[] topics;
        public string[] types;

        public TopicsResponse()
        {
            this.topics = new string[0];
            this.types = new string[0];
        }

        public TopicsResponse(string[] topics, string[] types)
        {
            this.topics = topics;
            this.types = types;
        }

        public static TopicsResponse Deserialize(MessageDeserializer deserializer) => new TopicsResponse(deserializer);

        private TopicsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topics, deserializer.ReadLength());
            deserializer.Read(out this.types, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
            serializer.WriteLength(this.types);
            serializer.Write(this.types);
        }

        public override string ToString()
        {
            return "TopicsResponse: " +
            "\ntopics: " + System.String.Join(", ", topics.ToList()) +
            "\ntypes: " + System.String.Join(", ", types.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
