//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TopicsAndRawTypesResponse : Message
    {
        public const string k_RosMessageName = "rosapi/TopicsAndRawTypes";
        public override string RosMessageName => k_RosMessageName;

        public string[] topics;
        public string[] types;
        public string[] typedefs_full_text;

        public TopicsAndRawTypesResponse()
        {
            this.topics = new string[0];
            this.types = new string[0];
            this.typedefs_full_text = new string[0];
        }

        public TopicsAndRawTypesResponse(string[] topics, string[] types, string[] typedefs_full_text)
        {
            this.topics = topics;
            this.types = types;
            this.typedefs_full_text = typedefs_full_text;
        }

        public static TopicsAndRawTypesResponse Deserialize(MessageDeserializer deserializer) => new TopicsAndRawTypesResponse(deserializer);

        private TopicsAndRawTypesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.topics, deserializer.ReadLength());
            deserializer.Read(out this.types, deserializer.ReadLength());
            deserializer.Read(out this.typedefs_full_text, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.topics);
            serializer.Write(this.topics);
            serializer.WriteLength(this.types);
            serializer.Write(this.types);
            serializer.WriteLength(this.typedefs_full_text);
            serializer.Write(this.typedefs_full_text);
        }

        public override string ToString()
        {
            return "TopicsAndRawTypesResponse: " +
            "\ntopics: " + System.String.Join(", ", topics.ToList()) +
            "\ntypes: " + System.String.Join(", ", types.ToList()) +
            "\ntypedefs_full_text: " + System.String.Join(", ", typedefs_full_text.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
