//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryActionResultMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectoryActionResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalStatusMsg status;
        public ExecuteTrajectoryResultMsg result;

        public ExecuteTrajectoryActionResultMsg()
        {
            this.header = new HeaderMsg();
            this.status = new Actionlib.GoalStatusMsg();
            this.result = new ExecuteTrajectoryResultMsg();
        }

        public ExecuteTrajectoryActionResultMsg(HeaderMsg header, Actionlib.GoalStatusMsg status, ExecuteTrajectoryResultMsg result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }

        public static ExecuteTrajectoryActionResultMsg Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryActionResultMsg(deserializer);

        private ExecuteTrajectoryActionResultMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.status = Actionlib.GoalStatusMsg.Deserialize(deserializer);
            this.result = ExecuteTrajectoryResultMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.result);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryActionResultMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nresult: " + result.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
