//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryActionFeedbackMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectoryActionFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public HeaderMsg header;
        public Actionlib.GoalStatusMsg status;
        public ExecuteTrajectoryFeedbackMsg feedback;

        public ExecuteTrajectoryActionFeedbackMsg()
        {
            this.header = new HeaderMsg();
            this.status = new Actionlib.GoalStatusMsg();
            this.feedback = new ExecuteTrajectoryFeedbackMsg();
        }

        public ExecuteTrajectoryActionFeedbackMsg(HeaderMsg header, Actionlib.GoalStatusMsg status, ExecuteTrajectoryFeedbackMsg feedback)
        {
            this.header = header;
            this.status = status;
            this.feedback = feedback;
        }

        public static ExecuteTrajectoryActionFeedbackMsg Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryActionFeedbackMsg(deserializer);

        private ExecuteTrajectoryActionFeedbackMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            this.status = Actionlib.GoalStatusMsg.Deserialize(deserializer);
            this.feedback = ExecuteTrajectoryFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.status);
            serializer.Write(this.feedback);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryActionFeedbackMsg: " +
            "\nheader: " + header.ToString() +
            "\nstatus: " + status.ToString() +
            "\nfeedback: " + feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
