//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryGoalMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectoryGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  The trajectory to execute
        public RobotTrajectoryMsg trajectory;

        public ExecuteTrajectoryGoalMsg()
        {
            this.trajectory = new RobotTrajectoryMsg();
        }

        public ExecuteTrajectoryGoalMsg(RobotTrajectoryMsg trajectory)
        {
            this.trajectory = trajectory;
        }

        public static ExecuteTrajectoryGoalMsg Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryGoalMsg(deserializer);

        private ExecuteTrajectoryGoalMsg(MessageDeserializer deserializer)
        {
            this.trajectory = RobotTrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryGoalMsg: " +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
