//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class ExecuteTrajectoryResultMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/ExecuteTrajectoryResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  Error code - encodes the overall reason for failure
        public MoveItErrorCodesMsg error_code;

        public ExecuteTrajectoryResultMsg()
        {
            this.error_code = new MoveItErrorCodesMsg();
        }

        public ExecuteTrajectoryResultMsg(MoveItErrorCodesMsg error_code)
        {
            this.error_code = error_code;
        }

        public static ExecuteTrajectoryResultMsg Deserialize(MessageDeserializer deserializer) => new ExecuteTrajectoryResultMsg(deserializer);

        private ExecuteTrajectoryResultMsg(MessageDeserializer deserializer)
        {
            this.error_code = MoveItErrorCodesMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_code);
        }

        public override string ToString()
        {
            return "ExecuteTrajectoryResultMsg: " +
            "\nerror_code: " + error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
