//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupGoalMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupGoal";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  Motion planning request to pass to planner
        public MotionPlanRequestMsg request;
        //  Planning options
        public PlanningOptionsMsg planning_options;

        public MoveGroupGoalMsg()
        {
            this.request = new MotionPlanRequestMsg();
            this.planning_options = new PlanningOptionsMsg();
        }

        public MoveGroupGoalMsg(MotionPlanRequestMsg request, PlanningOptionsMsg planning_options)
        {
            this.request = request;
            this.planning_options = planning_options;
        }

        public static MoveGroupGoalMsg Deserialize(MessageDeserializer deserializer) => new MoveGroupGoalMsg(deserializer);

        private MoveGroupGoalMsg(MessageDeserializer deserializer)
        {
            this.request = MotionPlanRequestMsg.Deserialize(deserializer);
            this.planning_options = PlanningOptionsMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
            serializer.Write(this.planning_options);
        }

        public override string ToString()
        {
            return "MoveGroupGoalMsg: " +
            "\nrequest: " + request.ToString() +
            "\nplanning_options: " + planning_options.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
