//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupActionMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public MoveGroupActionGoalMsg action_goal;
        public MoveGroupActionResultMsg action_result;
        public MoveGroupActionFeedbackMsg action_feedback;

        public MoveGroupActionMsg()
        {
            this.action_goal = new MoveGroupActionGoalMsg();
            this.action_result = new MoveGroupActionResultMsg();
            this.action_feedback = new MoveGroupActionFeedbackMsg();
        }

        public MoveGroupActionMsg(MoveGroupActionGoalMsg action_goal, MoveGroupActionResultMsg action_result, MoveGroupActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static MoveGroupActionMsg Deserialize(MessageDeserializer deserializer) => new MoveGroupActionMsg(deserializer);

        private MoveGroupActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = MoveGroupActionGoalMsg.Deserialize(deserializer);
            this.action_result = MoveGroupActionResultMsg.Deserialize(deserializer);
            this.action_feedback = MoveGroupActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "MoveGroupActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
