//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupSequenceActionMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupSequenceAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public MoveGroupSequenceActionGoalMsg action_goal;
        public MoveGroupSequenceActionResultMsg action_result;
        public MoveGroupSequenceActionFeedbackMsg action_feedback;

        public MoveGroupSequenceActionMsg()
        {
            this.action_goal = new MoveGroupSequenceActionGoalMsg();
            this.action_result = new MoveGroupSequenceActionResultMsg();
            this.action_feedback = new MoveGroupSequenceActionFeedbackMsg();
        }

        public MoveGroupSequenceActionMsg(MoveGroupSequenceActionGoalMsg action_goal, MoveGroupSequenceActionResultMsg action_result, MoveGroupSequenceActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static MoveGroupSequenceActionMsg Deserialize(MessageDeserializer deserializer) => new MoveGroupSequenceActionMsg(deserializer);

        private MoveGroupSequenceActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = MoveGroupSequenceActionGoalMsg.Deserialize(deserializer);
            this.action_result = MoveGroupSequenceActionResultMsg.Deserialize(deserializer);
            this.action_feedback = MoveGroupSequenceActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "MoveGroupSequenceActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
