//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class MoveGroupSequenceResultMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/MoveGroupSequenceResult";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        //  Response comprising information on all sections of the sequence
        public MotionSequenceResponseMsg response;

        public MoveGroupSequenceResultMsg()
        {
            this.response = new MotionSequenceResponseMsg();
        }

        public MoveGroupSequenceResultMsg(MotionSequenceResponseMsg response)
        {
            this.response = response;
        }

        public static MoveGroupSequenceResultMsg Deserialize(MessageDeserializer deserializer) => new MoveGroupSequenceResultMsg(deserializer);

        private MoveGroupSequenceResultMsg(MessageDeserializer deserializer)
        {
            this.response = MotionSequenceResponseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response);
        }

        public override string ToString()
        {
            return "MoveGroupSequenceResultMsg: " +
            "\nresponse: " + response.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
