//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class PickupActionMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/PickupAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PickupActionGoalMsg action_goal;
        public PickupActionResultMsg action_result;
        public PickupActionFeedbackMsg action_feedback;

        public PickupActionMsg()
        {
            this.action_goal = new PickupActionGoalMsg();
            this.action_result = new PickupActionResultMsg();
            this.action_feedback = new PickupActionFeedbackMsg();
        }

        public PickupActionMsg(PickupActionGoalMsg action_goal, PickupActionResultMsg action_result, PickupActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static PickupActionMsg Deserialize(MessageDeserializer deserializer) => new PickupActionMsg(deserializer);

        private PickupActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = PickupActionGoalMsg.Deserialize(deserializer);
            this.action_result = PickupActionResultMsg.Deserialize(deserializer);
            this.action_feedback = PickupActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "PickupActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
