//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Moveit
{
    [Serializable]
    public class PlaceActionMsg : Message
    {
        public const string k_RosMessageName = "moveit_msgs/PlaceAction";
        public override string RosMessageName => k_RosMessageName;

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PlaceActionGoalMsg action_goal;
        public PlaceActionResultMsg action_result;
        public PlaceActionFeedbackMsg action_feedback;

        public PlaceActionMsg()
        {
            this.action_goal = new PlaceActionGoalMsg();
            this.action_result = new PlaceActionResultMsg();
            this.action_feedback = new PlaceActionFeedbackMsg();
        }

        public PlaceActionMsg(PlaceActionGoalMsg action_goal, PlaceActionResultMsg action_result, PlaceActionFeedbackMsg action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }

        public static PlaceActionMsg Deserialize(MessageDeserializer deserializer) => new PlaceActionMsg(deserializer);

        private PlaceActionMsg(MessageDeserializer deserializer)
        {
            this.action_goal = PlaceActionGoalMsg.Deserialize(deserializer);
            this.action_result = PlaceActionResultMsg.Deserialize(deserializer);
            this.action_feedback = PlaceActionFeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.action_goal);
            serializer.Write(this.action_result);
            serializer.Write(this.action_feedback);
        }

        public override string ToString()
        {
            return "PlaceActionMsg: " +
            "\naction_goal: " + action_goal.ToString() +
            "\naction_result: " + action_result.ToString() +
            "\naction_feedback: " + action_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
