//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Rosapi
{
    [Serializable]
    public class TypeDefMsg : Message
    {
        public const string k_RosMessageName = "rosapi/TypeDef";
        public override string RosMessageName => k_RosMessageName;

        public string type;
        public string[] fieldnames;
        public string[] fieldtypes;
        public int[] fieldarraylen;
        public string[] examples;
        public string[] constnames;
        public string[] constvalues;

        public TypeDefMsg()
        {
            this.type = "";
            this.fieldnames = new string[0];
            this.fieldtypes = new string[0];
            this.fieldarraylen = new int[0];
            this.examples = new string[0];
            this.constnames = new string[0];
            this.constvalues = new string[0];
        }

        public TypeDefMsg(string type, string[] fieldnames, string[] fieldtypes, int[] fieldarraylen, string[] examples, string[] constnames, string[] constvalues)
        {
            this.type = type;
            this.fieldnames = fieldnames;
            this.fieldtypes = fieldtypes;
            this.fieldarraylen = fieldarraylen;
            this.examples = examples;
            this.constnames = constnames;
            this.constvalues = constvalues;
        }

        public static TypeDefMsg Deserialize(MessageDeserializer deserializer) => new TypeDefMsg(deserializer);

        private TypeDefMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.type);
            deserializer.Read(out this.fieldnames, deserializer.ReadLength());
            deserializer.Read(out this.fieldtypes, deserializer.ReadLength());
            deserializer.Read(out this.fieldarraylen, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.examples, deserializer.ReadLength());
            deserializer.Read(out this.constnames, deserializer.ReadLength());
            deserializer.Read(out this.constvalues, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.type);
            serializer.WriteLength(this.fieldnames);
            serializer.Write(this.fieldnames);
            serializer.WriteLength(this.fieldtypes);
            serializer.Write(this.fieldtypes);
            serializer.WriteLength(this.fieldarraylen);
            serializer.Write(this.fieldarraylen);
            serializer.WriteLength(this.examples);
            serializer.Write(this.examples);
            serializer.WriteLength(this.constnames);
            serializer.Write(this.constnames);
            serializer.WriteLength(this.constvalues);
            serializer.Write(this.constvalues);
        }

        public override string ToString()
        {
            return "TypeDefMsg: " +
            "\ntype: " + type.ToString() +
            "\nfieldnames: " + System.String.Join(", ", fieldnames.ToList()) +
            "\nfieldtypes: " + System.String.Join(", ", fieldtypes.ToList()) +
            "\nfieldarraylen: " + System.String.Join(", ", fieldarraylen.ToList()) +
            "\nexamples: " + System.String.Join(", ", examples.ToList()) +
            "\nconstnames: " + System.String.Join(", ", constnames.ToList()) +
            "\nconstvalues: " + System.String.Join(", ", constvalues.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
