//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MasterControl
{
    [Serializable]
    public class VacuumStateMsg : Message
    {
        public const string k_RosMessageName = "master_control/VacuumState";
        public override string RosMessageName => k_RosMessageName;

        // ## Creates a message to store 2 bools to send to the gripper to control the vacuum
        // ## Vacuum state
        //  00 = Suck
        //  10 = Off
        //  11 = Blow
        //  01 = Off (invalid)
        public bool vacuum0;
        public bool vacuum1;

        public VacuumStateMsg()
        {
            this.vacuum0 = false;
            this.vacuum1 = false;
        }

        public VacuumStateMsg(bool vacuum0, bool vacuum1)
        {
            this.vacuum0 = vacuum0;
            this.vacuum1 = vacuum1;
        }

        public static VacuumStateMsg Deserialize(MessageDeserializer deserializer) => new VacuumStateMsg(deserializer);

        private VacuumStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.vacuum0);
            deserializer.Read(out this.vacuum1);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.vacuum0);
            serializer.Write(this.vacuum1);
        }

        public override string ToString()
        {
            return "VacuumStateMsg: " +
            "\nvacuum0: " + vacuum0.ToString() +
            "\nvacuum1: " + vacuum1.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
